# Generated by Django 3.2.6 on 2022-09-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_celebrities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Celebrities',
            new_name='Celebritie',
        ),
    ]
